### ISSUE TITLE
gym.GoalEnv decapricated from gym.version >= 0.21

### ISSUE THREAD

**Issue by michaelfeil** [rr-learning/CausalWorld#103]
```bash
CausalWorld/causal_world/wrappers/env_wrappers.py", line 6, in <module>
    class HERGoalEnvWrapper(gym.GoalEnv):
AttributeError: module 'gym' has no attribute 'GoalEnv'
```

gym.GoalEnv was removed with version 0.22: https://github.com/openai/gym/commit/616b07115871588a5b63fa470d4f554d114d3e25

**Comment by ftraeuble** [comment]
Thanks for spotting this! Closing this because it has been updated with the latest pull request.
